version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - DATABASE_URL=mongodb://mongo:27017/viralytix
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - mongo
      - redis
    networks:
      - viralytix-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    networks:
      - viralytix-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - viralytix-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - viralytix-network

networks:
  viralytix-network:
    driver: bridge

volumes:
  mongo-data:
  redis-data: